name: flutter_ai_agent_sdk
description: A high-performance, extensible AI Agent SDK for Flutter with voice interaction, LLM integration, and tool execution.
version: 1.0.0
homepage: https://github.com/Chief-Strategist-J/flutter_ai_agent_sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP & Networking
  http: ^1.1.0
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  
  # Audio Processing
  record: ^5.0.4
  audioplayers: ^5.2.1
  flutter_sound: ^9.2.13
  
  # Speech Recognition
  speech_to_text: ^6.6.0
  
  # Text to Speech
  flutter_tts: ^4.0.2
  
  # State Management
  rxdart: ^0.27.7
  
  # JSON & Serialization
  json_annotation: ^4.8.1
  
  # Utilities
  uuid: ^4.2.2
  collection: ^1.18.0
  async: ^2.11.0
  path_provider: ^2.1.1
  
  # Logging
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  test: ^1.24.9
  fake_async: ^1.3.1
  mocktail: ^1.0.1
  coverage: ^1.7.1

flutter:
  plugin:
    platforms:
      android:
        package: com.yourorg.flutter_ai_agent_sdk
        pluginClass: FlutterAiAgentSdkPlugin
      ios:
        pluginClass: FlutterAiAgentSdkPlugin
